### PR TITLE
Add Iris template

### PR DESCRIPTION
**Pull request by kataras**
- Framework website: https://www.iris-go.com
- GitHub Repository: https://github.com/kataras

The code contains an example of testing http requests with Iris too.

### CODE REVIEW

**Comment by rade-microtica** [comment]
Hi @kataras,

Thank for contributing to the open-source templates library!

We'll review and test the pull request in the upcoming days and publish the template in Microtica app.

I will keep you posted.

**Comment by kataras** [comment]
Thanks @rade-microtica

**Comment by kataras** [comment]
Thanks for the merge @rade-microtica, do you know when Iris will be shown at: https://microtica.com/ so I can start sharing the web link?

**Comment by rade-microtica** [comment]
@kataras, the release of the Iris template on [microtica.com](https://microtica.com/) is scheduled for Tuesday next week (4 Oct).

Once ready, I will share all relevant links (website, docs etc.) here.

Thanks again for the contribution! 🙏

**Pull request merged**
